# Project 3: Part 3 Modeling

In [66]:
import pandas as pd
import matplotlib.pyplot as plt
from patsy import dmatrix
import datetime as dt
import numpy as np
import pickle

%matplotlib inline

from sklearn import metrics

import seaborn as sns
from sklearn.cross_validation import train_test_split


In [67]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import naive_bayes

In [98]:
with open("users.pkl", 'rb') as picklefile: 
    users = pickle.load(picklefile)

In [99]:
y = users['US']
users = users.drop('US', axis = 1)

In [100]:
users = users.drop('id',axis = 1)

In [105]:
users.head()

gender_FEMALE  gender_MALE  gender_OTHER  language_cs  language_da  \
0              0            1             0            0            0   
1              0            0             0            0            0   
2              1            0             0            0            0   
3              0            0             0            0            0   
4              1            0             0            0            0   

   language_de  language_el  language_en  language_es  language_fi  ...   \
0            0            0            1            0            0  ...    
1            0            0            1            0            0  ...    
2            0            0            1            0            0  ...    
3            0            0            1            0            0  ...    
4            0            0            1            0            0  ...    

   affiliate_provider_yandex  first_affiliate_tracked_local ops  \
0                          0                                  0   
1                          0                                  0   
2                          0                                  0   
3                          0                                  0   
4                          0                                  0   

   first_affiliate_tracked_marketing  first_affiliate_tracked_omg  \
0                                  0                            1   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   first_affiliate_tracked_product  first_affiliate_tracked_tracked-other  \
0                                0                                      0   
1                                0                                      0   
2                                0                                      0   
3                                0                                      0   
4                                0                                      0   

   first_affiliate_tracked_untracked  diff_account_to_first_active  count  \
0                                  0                            -1    127   
1                                  1                            -1      8   
2                                  0                            -1      7   
3                                  1                            -1     43   
4                                  1                            -1      8   

    age  
0  56.0  
1  42.0  
2  41.0  
3   NaN  
4  46.0  

[5 rows x 109 columns]

In [106]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: US, dtype: uint8

In [122]:
xtrain, xtest, ytrain, ytest = train_test_split(users.iloc[:,:-1], y, test_size=0.2, random_state = 1234)

In [123]:
xtrain.head()

gender_FEMALE  gender_MALE  gender_OTHER  language_cs  language_da  \
23905              0            0             0            0            0   
22695              0            0             0            0            0   
5905               0            0             0            0            0   
23565              1            0             0            0            0   
17907              0            0             0            0            0   

       language_de  language_el  language_en  language_es  language_fi  ...    \
23905            0            0            1            0            0  ...     
22695            0            0            1            0            0  ...     
5905             0            0            1            0            0  ...     
23565            0            0            1            0            0  ...     
17907            0            0            1            0            0  ...     

       affiliate_provider_yahoo  affiliate_provider_yandex  \
23905                         0                          0   
22695                         0                          0   
5905                          0                          0   
23565                         0                          0   
17907                         0                          0   

       first_affiliate_tracked_local ops  first_affiliate_tracked_marketing  \
23905                                  0                                  0   
22695                                  0                                  0   
5905                                   0                                  0   
23565                                  0                                  0   
17907                                  0                                  0   

       first_affiliate_tracked_omg  first_affiliate_tracked_product  \
23905                            0                                0   
22695                            0                                0   
5905                             0                                0   
23565                            0                                0   
17907                            0                                0   

       first_affiliate_tracked_tracked-other  \
23905                                      0   
22695                                      0   
5905                                       0   
23565                                      0   
17907                                      0   

       first_affiliate_tracked_untracked  diff_account_to_first_active  count  
23905                                  0                            -1     17  
22695                                  0                            -1     19  
5905                                   0                            -1      2  
23565                                  0                            -1    125  
17907                                  1                            -1     15  

[5 rows x 108 columns]

## KNN

In [ ]:
normalizer = preprocessing.Normalizer()
X_norm = normalizer.fit_transform(X)

## Logistic Regression

In [124]:
lr = LogisticRegression()
lr.fit(xtrain, ytrain)
y_pred = lr.predict(xtest)

print("Accuracy: %.3f"% metrics.accuracy_score(ytest, lr.predict(xtest)))
print(metrics.classification_report(ytest, lr.predict(xtest)))
print(metrics.confusion_matrix(ytest,lr.predict(xtest)))

Accuracy: 0.705
             precision    recall  f1-score   support

          0       0.00      0.00      0.00      1695
          1       0.71      1.00      0.83      4060

avg / total       0.50      0.71      0.58      5755

[[   0 1695]
 [   1 4059]]


## Random Forests

In [128]:
rf = RandomForestClassifier()
rf.fit(xtrain, ytrain)
y_pred = rf.predict(xtest)

print("Accuracy: %.3f"% metrics.accuracy_score(ytest, rf.predict(xtest)))
print(metrics.classification_report(ytest, rf.predict(xtest)))
print(metrics.confusion_matrix(ytest,rf.predict(xtest)))

Accuracy: 0.597
             precision    recall  f1-score   support

          0       0.29      0.26      0.27      1695
          1       0.70      0.74      0.72      4060

avg / total       0.58      0.60      0.59      5755

[[ 438 1257]
 [1060 3000]]


In [126]:
features = pd.DataFrame()
features['importances'] = rf.feature_importances_
features['features'] = users.columns[:-1]
features.sort_values('importances',ascending = False)

importances                               features
107     0.777719                                  count
25      0.023417                 signup_method_facebook
105     0.020181      first_affiliate_tracked_untracked
1       0.018350                            gender_MALE
0       0.016374                          gender_FEMALE
102     0.009592            first_affiliate_tracked_omg
44      0.008126                   first_browser_Chrome
32      0.006877          first_device_type_Mac Desktop
49      0.006544                  first_browser_Firefox
35      0.006510      first_device_type_Windows Desktop
81      0.005645            affiliate_channel_sem-brand
58      0.005060            first_browser_Mobile Safari
66      0.004906                   first_browser_Safari
28      0.004727                         signup_app_Web
7       0.004598                            language_en
104     0.004535  first_affiliate_tracked_tracked-other
82      0.004456        affiliate_channel_sem-non-brand
29      0.004197                         signup_app_iOS
51      0.004119                       first_browser_IE
91      0.003669              affiliate_provider_google
37      0.003464               first_device_type_iPhone
103     0.003207        first_affiliate_tracked_product
36      0.003090                 first_device_type_iPad
27      0.003015                       signup_app_Moweb
83      0.002880                  affiliate_channel_seo
45      0.002622            first_browser_Chrome Mobile
87      0.002488              affiliate_provider_direct
80      0.002448          affiliate_channel_remarketing
24      0.002435                            language_zh
33      0.002263        first_device_type_Other/Unknown
..           ...                                    ...
92      0.000076                 affiliate_provider_gsp
18      0.000075                            language_pl
3       0.000063                            language_cs
23      0.000056                            language_tr
71      0.000050           first_browser_Sogou Explorer
9       0.000046                            language_fi
93      0.000038              affiliate_provider_meetup
42      0.000031       first_browser_BlackBerry Browser
40      0.000014               first_browser_Apple Mail
69      0.000014                first_browser_SiteKiosk
74      0.000013         first_browser_TheWorld Browser
73      0.000012               first_browser_TenFourFox
12      0.000004                            language_is
106     0.000000           diff_account_to_first_active
60      0.000000              first_browser_NetNewsWire
41      0.000000            first_browser_Avant Browser
85      0.000000          affiliate_provider_craigslist
59      0.000000                  first_browser_Mozilla
43      0.000000                   first_browser_Camino
47      0.000000                first_browser_CometBird
48      0.000000                 first_browser_CoolNovo
50      0.000000                first_browser_Googlebot
75      0.000000           first_browser_Yandex.Browser
72      0.000000                first_browser_Stainless
70      0.000000              first_browser_SlimBrowser
55      0.000000           first_browser_Kindle Browser
64      0.000000     first_browser_Palm Pre web browser
63      0.000000                first_browser_Pale Moon
62      0.000000               first_browser_Opera Mini
54      0.000000                     first_browser_Iron

[108 rows x 2 columns]

## SVMs

In [ ]:
#normalizer = preprocessing.Normalizer()
#X_norm = normalizer.fit_transform(X)

## Naive Bayes

### Gaussian

In [129]:
nb_g = naive_bayes.GaussianNB()
nb_g.fit(xtrain, ytrain)

print("Accuracy: %.3f"% metrics.accuracy_score(ytest, nb_g.predict(xtest)))
print(metrics.classification_report(ytest, nb_g.predict(xtest)))
print(metrics.confusion_matrix(ytest,nb_g.predict(xtest)))

Accuracy: 0.646
             precision    recall  f1-score   support

          0       0.30      0.15      0.20      1695
          1       0.71      0.85      0.77      4060

avg / total       0.59      0.65      0.61      5755

[[ 261 1434]
 [ 603 3457]]


### Bernoulli

In [130]:
nb_b = naive_bayes.BernoulliNB()
nb_b.fit(xtrain, ytrain)

print("Accuracy: %.3f"% metrics.accuracy_score(ytest, nb_b.predict(xtest)))
print(metrics.classification_report(ytest, nb_b.predict(xtest)))
print(metrics.confusion_matrix(ytest,nb_b.predict(xtest)))

Accuracy: 0.704
             precision    recall  f1-score   support

          0       0.20      0.00      0.00      1695
          1       0.71      1.00      0.83      4060

avg / total       0.56      0.70      0.58      5755

[[   3 1692]
 [  12 4048]]


### Multinomial

In [115]:
nb_m = naive_bayes.MultinomialNB()
nb_m.fit(xtrain, ytrain)

print("Accuracy: %.3f"% metrics.accuracy_score(ytest, nb_m.predict(xtest)))
print(metrics.classification_report(ytest, nb_m.predict(xtest)))

ValueError: Input X must be non-negative

In [53]:
users

id   age  signup_flow  FEMALE  MALE  basic  facebook  google  \
0      d1mm9tcy42  62.0            0       0     1      1         0       0   
1      4rvqpxoh3h   NaN           25       0     0      1         0       0   
2      xwxei6hdk4  32.0            0       1     0      0         1       0   
3      ro2stddszp  19.0            0       0     0      1         0       0   
4      awiurksqr3  32.0            0       1     0      0         1       0   
5      ucgks2fyez  76.0            0       0     0      1         0       0   
6      jrqykh9y8x  27.0            0       1     0      0         1       0   
7      s9xrwtyzsq  30.0            0       0     1      1         0       0   
8      11581i5wng   NaN            0       0     0      1         0       0   
9      oa8oz6sj6s  40.0            0       0     1      1         0       0   
10     nmptg2k3tj   NaN            0       0     0      1         0       0   
11     9v9pjiw5s1  25.0            0       0     1      1         0       0   
12     1g18fjgi2m  35.0            0       1     0      1         0       0   
13     psn48sflyc  29.0           25       0     1      1         0       0   
14     msfo4las9k  60.0            0       0     1      1         0       0   
15     iwx2u1gzyu   NaN           12       0     1      0         1       0   
16     4n32dm2435  42.0            0       0     1      1         0       0   
17     ixmk7qm5cv   NaN            0       0     0      1         0       0   
18     mrvjvk6ycy  22.0            0       0     1      0         1       0   
19     stiseqi6h6   NaN            0       0     0      1         0       0   
20     d6r5a2l398  25.0           12       0     1      0         1       0   
21     2pw9yjm8aq   NaN            0       0     0      1         0       0   
22     uyb283j6j0   NaN           25       0     0      1         0       0   
23     d9no5qj7ie   NaN            0       0     0      1         0       0   
24     yetxlyyeja  34.0            0       0     1      1         0       0   
25     cm0nbuxqmw   NaN            0       0     0      1         0       0   
26     ne62ok6xaf  35.0           12       0     1      0         1       0   
27     ccl1h3nes7  47.0           24       0     1      1         0       0   
28     8t8xs697my   NaN            0       0     0      1         0       0   
29     0e9rascg0c   NaN            0       0     0      1         0       0   
...           ...   ...          ...     ...   ...    ...       ...     ...   
28744  auafpy23gk  29.0            0       1     0      1         0       0   
28745  g6sulrjk7c  33.0            0       0     1      0         1       0   
28746  q7s9qir6xu   NaN            0       0     0      1         0       0   
28747  d339w9196p  27.0            0       0     1      1         0       0   
28748  5ljgd6ldv8   NaN            0       0     0      1         0       0   
28749  0co6s86hgb  41.0            0       0     1      0         1       0   
28750  67jxj3h7uf   NaN            0       0     0      1         0       0   
28751  i1lzm2k3wr   NaN            0       0     0      1         0       0   
28752  nhtc9mxlp7  38.0            0       1     0      1         0       0   
28753  bzcqek3k51  22.0           25       0     1      1         0       0   
28754  3yew808eqp  39.0           25       1     0      1         0       0   
28755  gedoe2zmrj  30.0            0       1     0      1         0       0   
28756  c999p94qui  30.0            0       1     0      1         0       0   
28757  lc6apdi0hc  39.0            0       0     0      1         0       0   
28758  x17avasiuk  53.0           23       0     1      1         0       0   
28759  xif0n17eof  45.0            0       0     0      1         0       0   
28760  jfcwjhkmtv  32.0            0       0     1      0         1       0   
28761  e5ysdcsb2v   NaN            0       0     0      1         0       0   
28762  5q5k8aov71  23.0            0       0     0      1        